AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  RequestsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: RequestsLayer
      Description: Lambda layer with requests library
      ContentUri: requests-layer/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Delete

  DatabaseLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PopulateDatabase # Name of the function
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: ./
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource: 
              - arn:aws:ssm:us-east-2:036134507423:parameter/myapp/*
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
          Resource:
            - arn:aws:s3:::trazability/*
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /populate
            Method: POST
      Layers:
        - Ref: RequestsLayer  # Attach the requests layer