AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DatabaseLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PopulateDatabase # Name of the function
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: ./
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /populate
            Method: POST
